name: todoey
description: A new Flutter application.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2

  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
  - images/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: PermanentMarker
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf

    - family: YujiMai
      fonts:
        - asset: fonts/YujiMai-Regular.ttf